# Generated by Django 5.0.3 on 2024-03-23 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picha',
            name='added_to_site',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pics.addedtowebsite'),
            preserve_default=False,
        ),
    ]
