# Generated by Django 5.0.3 on 2024-03-23 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0002_picha_added_to_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picha',
            name='added_to_site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pics.addedtowebsite'),
        ),
    ]
