# Generated by Django 5.0.3 on 2024-03-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0003_alter_picha_added_to_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picha',
            name='added_to_site',
        ),
        migrations.AddField(
            model_name='picha',
            name='shopify_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='picha',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='AddedToWebsite',
        ),
    ]
