# Generated by Django 5.0.3 on 2024-03-23 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0004_remove_picha_added_to_site_picha_shopify_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picha',
            old_name='status',
            new_name='added_to_website',
        ),
    ]
