# Generated by Django 5.0.3 on 2024-04-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0007_alter_picha_shopify_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='uploads/collections')),
            ],
        ),
        migrations.CreateModel(
            name='FlowerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='uploads/flower_types')),
            ],
        ),
        migrations.AlterField(
            model_name='picha',
            name='image',
            field=models.ImageField(upload_to='uploads/flowers'),
        ),
        migrations.AlterField(
            model_name='picha',
            name='shopify_url',
            field=models.URLField(blank=True, default='No URL was provided'),
        ),
        migrations.AddField(
            model_name='picha',
            name='collection',
            field=models.ManyToManyField(to='pics.collection'),
        ),
        migrations.AddField(
            model_name='picha',
            name='flower_type',
            field=models.ManyToManyField(to='pics.flowertype'),
        ),
    ]
