# Generated by Django 5.0.3 on 2024-04-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0008_collection_flowertype_alter_picha_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picha',
            name='collection',
            field=models.ManyToManyField(default='no_collection', to='pics.collection'),
        ),
        migrations.AlterField(
            model_name='picha',
            name='flower_type',
            field=models.ManyToManyField(default='no_flower_type', to='pics.flowertype'),
        ),
    ]
