# Generated by Django 5.0.3 on 2024-04-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0009_alter_picha_collection_alter_picha_flower_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='picha',
            name='edited_image',
            field=models.ImageField(blank=True, upload_to='uploads/edited_images'),
        ),
    ]
