# Generated by Django 5.0.3 on 2024-04-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0010_picha_edited_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picha',
            name='added_to_website',
        ),
        migrations.AlterField(
            model_name='picha',
            name='shopify_url',
            field=models.URLField(blank=True),
        ),
    ]
